### ISSUE TITLE
日志中时间显示错误

### ISSUE THREAD

**Issue by cnzixn** [opq-osc/OPQ#11]
./OPQBot                                                    
2020/12/31 00:57:29.482 [C]  Download LuaPackage Done! v6.0.6
2020/12/31 00:57:29.485 [W]  ClusterIP 0.0.0.0:8888  WorkerThread 50
上面是部分日志代码，当前时间为2020/12/31 09:00:00，日志中的时间显示错误，重启也没用。

**Comment by Teeoo** [comment]
不如看看你服务器时间是否正确？
