### ISSUE TITLE
发送消息成功 成功 有时报错，报错后一直报错，重新安装后正常 然后报错

### ISSUE THREAD

**Issue by worker1024** [opq-osc/OPQ#13]
nterfaceconversion: interface{
    
}isnil,
notstringstacktraceback: [
    G
]: infunction'Api_SendMsgV2'/Qbot/WebPlugins/Api_LuaCaller.lua: 60: infunction'fSwitch'/Qbot/WebPlugins/Api_LuaCaller.lua: 196: inmainchunk[
    G
]: ?

**Comment by Teeoo** [comment]
> nterfaceconversion: interface{
> 
> }isnil,
> notstringstacktraceback: [
> G
> ]: infunction'Api_SendMsgV2'/Qbot/WebPlugins/Api_LuaCaller.lua: 60: infunction'fSwitch'/Qbot/WebPlugins/Api_LuaCaller.lua: 196: inmainchunk[
> G
> ]: ?

什么平台,有什么插件,请复现步骤

**Comment by worker1024** [comment]
linux centos 8.2  安装的是6.0.6 arm64版本，除自带的三个插件未安装其他插件。使用webapi发送好友消息时候出现此报错。
http://127.0.0.1:8888/v1/LuaApiCaller?qq=********&funcname=SendMsgV2

**Comment by worker1024** [comment]
除基本配置外未对opqbot做任何修改 ，之前发送消息正常，修改了待提交的json内容后出现报错，此后一直同样报错。

**Comment by Teeoo** [comment]
> 除基本配置外未对opqbot做任何修改 ，之前发送消息正常，修改了待提交的json内容后出现报错，此后一直同样报错。

看看json
