### ISSUE TITLE
登录时提示unexpected character

### ISSUE THREAD

**Issue by yuezhenglingluan** [opq-osc/OPQ#21]
![image](https://user-images.githubusercontent.com/42693943/110263094-9dcf8b80-7f83-11eb-8f3e-f76a2bf2622d.png)
扫码登陆后出现如图所示的错误

**Comment by Teeoo** [comment]
说出来你可能不信,我刚在tg回答完你问题

**Comment by yuezhenglingluan** [comment]
> 说出来你可能不信,我刚在tg回答完你问题

啊这

**Comment by Teeoo** [comment]
理论上这是正常情况,应该是vm解析lua的时候某个地方语法错误了 不影响正常运行
