### ISSUE TITLE
运行机器人报错

### ISSUE THREAD

**Issue by Lindsay284** [opq-osc/OPQ#30]
想请问一下作者，为什么我运行机器人的时候会报错呢，错误
CheckLua Err unexpected end of JSON input
conf文件设置如下
![~Y`6QT~VR47$Z`5GYY$EZL](https://user-images.githubusercontent.com/55623072/139697662-f641a368-4cba-415a-8dde-7b90de84ed8b.png)
另外不太清楚这个SocketIOUrl是什么所以没有填，感觉就是这里出了问题

**Comment by mcoo** [comment]
升级一下最新版opqbot，这个url一般不需要填，请看wiki里的主动socketio 大概好像是吧～(￣▽￣～)~
