### ISSUE TITLE
2022/05/18 20:50:30.363 [C]  下载文件失败 2022/05/18 20:50:31.004 [C]  下载不存在文件 https://cdn.jsdelivr.net/gh/OPQBOT/OPQ@845e0b99f9f38a88624bac01811dc69d829af923//Api_LuaCaller.lua

### ISSUE THREAD

**Issue by altair520** [opq-osc/OPQ#39]
2022/05/18 20:50:30.363 [C]  下载文件失败
2022/05/18 20:50:31.004 [C]  下载不存在文件 https://cdn.jsdelivr.net/gh/OPQBOT/OPQ@845e0b99f9f38a88624bac01811dc69d829af923//Api_LuaCaller.lua

**Comment by fz6m** [comment]
Try ping `test1.jsdelivr.net` or other not DNS pollution url get server raw ip :

 - CloudFlare：`test1.jsdelivr.net`

 - CloudFlare：`testingcf.jsdelivr.net`

 - Fastly：`fastly.jsdelivr.net`

 - GCORE：`gcore.jsdelivr.net`


```bash
ping test1.jsdelivr.net
```

Make a host map :

```bash
# hosts

104.16.86.20     cdn.jsdelivr.net
# ...
```

**Comment by History-exe** [comment]
添加了hosts也还是不能下载。修改hosts之后已经开启飞行模式一次。
但是却可以通过浏览器下载的方式一个一个的下载，有点奇怪。

系统：Ubuntu 20.04
网络：手机流量热点，手机上开启代理共享给电脑。

**Comment by fz6m** [comment]
> 添加了hosts也还是不能下载。修改hosts之后已经开启飞行模式一次。 但是却可以通过浏览器下载的方式一个一个的下载，有点奇怪。
> 
> 系统：Ubuntu 20.04 网络：手机流量热点，手机上开启代理共享给电脑。

你应该在服务器上部署，通过拷贝 cookie 等方式解决同网络问题，而 hosts 问题则通过配置服务器的 hosts 文件解决。
