### ISSUE TITLE
./OPQBot运行时无法下载缺失文件

### ISSUE THREAD

**Issue by NooAcc** [opq-osc/OPQ#41]
jsdelivr不是寄了嘛，所以运行./OPQBot时一直显示：
“下载不存在文件 https://cdn.jsdelivr.net/gh/OPQBOT/OPQ@845e0b99f9f38a88624bac01811dc69d829af923//Api_LuaCaller.lua”

**Comment by mcoo** [comment]
请查看 #40

**Comment by H1W0XXX** [comment]
网页上能打开,但是程序运行提示找不到文件

**Comment by Teeoo** [comment]
> 网页上能打开,但是程序运行提示找不到文件

不如试试把你终端代理下？

**Comment by H1W0XXX** [comment]
更新以后token变成空白了,填上token就好了
