### ISSUE TITLE
有微信的机器人么？

### ISSUE THREAD

**Issue by bluce** [opq-osc/OPQ#42]
### 事先确认项

- [ ] 我确定该反馈是新的，没有和 issue 列表中已有的问题重复
- [ ] 我确定查阅过了 官方文档、OPQBot 文档 等所有的信息来源
- [ ] 我确定我使用的 QPQBot 是最新版本

### OPQBot 版本

1

### 系统架构

1

### 错误描述

1

### 重现步骤

1. 
2. 
3. 
...

**Comment by xiyaowong** [comment]
readme都没看完
