### ISSUE TITLE
./OPQBot失败

### ISSUE THREAD

**Issue by iTeraxo** [opq-osc/OPQ#47]
### 事先确认项

- [X] 我确定该反馈是新的，没有和 issue 列表中已有的问题重复
- [X] 我确定查阅过了 官方文档、OPQBot 文档 等所有的信息来源
- [X] 我确定我使用的 QPQBot 是最新版本

### OPQBot 版本

OPQBot_6.7.5-20220624_linux_amd64

### 系统架构

Linux

### 错误描述

错误日志：
2022/07/04 04:49:47.846 [C]  下载Config.json文件失败 (网络错误或未安装wget)
2022/07/04 04:49:47.846 [W]  ClusterIP 0.0.0.0:8888  WorkerThread 50 CurrentClientIP
服务器网络是正常的，有wget

### 重现步骤

1. 
2. 
3. 
...

**Comment by Teeoo** [comment]
#39

**Comment by iTeraxo** [comment]
> #39

已经修改host后还是不可以

**Comment by mcoo** [comment]
> > #39
> 
> 已经修改host后还是不可以

首先你需要确保 `wget` 工具是否可用，然后确保自己能够连接上 `test1.jsdelivr.net` 网络，测试 wget 如果出现
```
 Wget error: ERROR: The certificate of is not trusted.
```
请安装证书
```
sudo apt-get install ca-certificates
```

如果你不会安装 Wget：
[Docker安装教程](https://docs.opqbot.com/guide/docker-start.html)

**Comment by natsu1949** [comment]
wget可用，test1.jsdelivr.net可以连接，host也修改了，实在不知道哪里的问题了

**Comment by iTeraxo** [comment]
> > > #39
> > 
> > 
> > 已经修改host后还是不可以
> 
> 首先你需要确保 `wget` 工具是否可用，然后确保自己能够连接上 `test1.jsdelivr.net` 网络，测试 wget 如果出现
> 
> ```
>  Wget error: ERROR: The certificate of is not trusted.
> ```
> 
> 请安装证书
> 
> ```
> sudo apt-get install ca-certificates
> ```
> 
> 如果你不会安装 Wget： [Docker安装教程](https://docs.opqbot.com/guide/docker-start.html)

wget可用，test1.jsdelivr.net可以连接，host也修改了，实在不知道哪里的问题了

**Comment by mcoo** [comment]
你先用docker安装试一下排除一下wget的问题，如果一样那就是网络的问题，那就弄一下代理。
