### ISSUE TITLE
私聊报错

### ISSUE THREAD

**Issue by guyuexue** [opq-osc/OPQ#49]
### 事先确认项

- [X] 我确定该反馈是新的，没有和 issue 列表中已有的问题重复
- [X] 我确定查阅过了 官方文档、OPQBot 文档 等所有的信息来源
- [X] 我确定我使用的 QPQBot 是最新版本

### OPQBot 版本

v6.7.5

### 系统架构

linux/amd64

### 错误描述

之前一直平稳运行,正常用的,最近开始私聊会报错
![image](https://user-images.githubusercontent.com/16451026/178088535-9bd4ffdf-54ad-4be6-a08e-bc0ae9a64faf.png)

### Logs

![image](https://user-images.githubusercontent.com/16451026/178088479-5eb746e6-54f0-437c-8b50-677fba455b42.png)

### 重现步骤

1. 给机器人qq发私聊消息
2. 
3. 
...

**Comment by HuXioAn** [comment]
最近也遇到这个问题，之前一直比较平稳。
