### ISSUE TITLE
真NB，把群给聊没了

### ISSUE THREAD

**Issue by gmsicu** [opq-osc/OPQ#53]
### 事先确认项

- [X] 我确定该反馈是新的，没有和 issue 列表中已有的问题重复
- [X] 我确定查阅过了 官方文档、OPQBot 文档 等所有的信息来源
- [X] 我确定我使用的 QPQBot 是最新版本

### OPQBot 版本

6666

### 系统架构

gg/gg

### 错误描述

有新群了戳我

### 重现步骤

1. 
2. 
3. 
...

**Comment by fz6m** [comment]
后续消息会在 TG 群同步。

**Comment by xiyaowong** [comment]
老实交代，你是不是内鬼？（误伤抱歉）
