### ISSUE TITLE
OPQ登录失败

### ISSUE THREAD

**Issue by Fhm-newbie** [opq-osc/OPQ#58]
### 事先确认项

- [x] 我确定该反馈是新的，没有和 issue 列表中已有的问题重复
- [x] 我确定查阅过了 官方文档、OPQBot 文档 等所有的信息来源
- [x] 我确定我使用的 QPQBot 是最新版本

### OPQBot 版本

v6.7.5-20230216

### 系统架构

Linux amd64

### 错误描述

OPQ无法正常登录，扫码确认登录后显示235错误，疑似是腾讯最新款的风控

### Logs

![image](https://user-images.githubusercontent.com/63446200/223600954-edc4e2e1-1c7a-48c7-97d1-4108e68e749b.png)
![image](https://user-images.githubusercontent.com/63446200/223600984-90f852dc-72cd-4dc0-b51d-6830557f8187.png)
oicq的235报错是这样
![image](https://user-images.githubusercontent.com/63446200/223601057-068c9499-ce0b-43e0-84b6-65755733a741.png)
oicq的解决方法是修改device文件后就能正常登录了，但是opq好像没有device

### 重现步骤

1. 输入./OPQ
2. 扫码登录
3. 报错235
...

### 其他

经个人体验，该种风控效果为：被风控的QQ必须使用最新版QQ软件才能登录，包括在我的个人电脑上，我自己的QQ是可以正常登录的，但是bot用QQ扫码会提示00020（下载最新版），下载最新版后可以正常登录

**Comment by CodFrm** [comment]
我也登录不上，难受

**Comment by xiyaowong** [comment]
无解，再等个把月

**Comment by ElieenAndBella** [comment]
已更新，可以close咯，亲。
