### ISSUE TITLE
发送群组卡片消息-JSON

### ISSUE THREAD

**Issue by Crow9527** [opq-osc/OPQ#64]
### 事先确认项

- [X] 我确定该反馈是新的，没有和 issue 列表中已有的问题重复
- [X] 我确定查阅过了 官方文档、OPQBot 文档 等所有的信息来源
- [X] 我确定我使用的 QPQBot 是最新版本

### OPQBot 版本

6.9.6

### 系统架构

linux/amd64

### 错误描述

卡片消息中的token如何生成

### 重现步骤

1. 
2. 
3. 
...

**Comment by fz6m** [comment]
card 消息内容完全取决于你自己的研究，没有生成这一说法。
